CREATE TABLE flags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  flag TINYINT(1) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
